version: '3'

services:
  core:
    image: microfrontends/core:latest
    ports:
    - 8080:80
    environment:
      SERVER_PORT: 80
  
  projectlist:
    image: microfrontends/projectlist:latest
    ports:
    - 8081:80
    environment:
      SERVER_PORT: 80
      SERVER_CONTEXT_PATH: /projectlist
      SERVICE_CORE: http://core

  reports:
    image: microfrontends/reports:latest
    ports:
    - 8082:80
    environment:
      SERVER_PORT: 80
      SERVER_CONTEXT_PATH: /reports
      SERVICE_CORE: http://core

  integration:
    image: microfrontends/integration:latest

  loadbalancer:
    image: microfrontends/loadbalancer:latest
    ports:
    - 80:80
